---
title: 'Final Project: COVID-19 Dataset'
author: 'The Lads: Frankie Willard, Manny Mokel, Alex Katopodis, Parker Dingman'
subtitle: Due Friday, November 20, 11:59 PM
output:
  pdf_document: default
  html_document: default
---

### Introduction


Throughout the year 2020, the COVID-19 pandemic took the world by storm, deeply impacting every country on the planet, albeit with differing degrees of severity. As cases continued to rise, families suffered from the loss of family members, jobs, social interactions, disposable income, and more. 

This public health crisis became severe enough such that many countries took decisive action, shutting down their economies to prioritize the lives of citizens. Meanwhile, other countries were less strict in their policies, attempting to preserve their economy at the potential expense of their citizen’s lives. The difference in each country’s characteristics, demographics, public health capacities, and the strictness of COVID-19 policies led to vastly different effects of the pandemic on different countries. Given our personal connections to the effects of the pandemic through our lives, our friends, and our families, we wanted to determine what led to the pandemic affecting some places worse than others.  

We are interested in investigating how a country's demographics impact the domestic severity of COVID-19. More specifically, we would like to see which demographics lead to higher cases per capita and deaths per case. 


------------------------------------
For our final project, we will be investigating country-level COVID-19 data to determine the relationship between their characteristics and demographics to virus transmission and deaths. By analyzing the effects of different country characteristics, we seek to determine specifically which variables are associated with stringency indexes, cases per capita, and deaths per case.

Research Question:

How do a country's characteristics, geography, and  demographics impact the strictness of their COVID policy, as well as the total spread and effects of COVID-19?


### Data Description

### Methodology

### Results

### Discussion



